package io.github.nyghtfull.util.io;

public class DataUtil {
    public static String[] commonNames = new String[] {
            "Serenity",
            "Ethereal",
            "Grace",
            "Charm",
            "Elegance",
            "Radiant",
            "Glimmer",
            "Whisper",
            "Enchant",
            "Tranquil",
            "Harmony",
            "Glow",
            "Velvet",
            "Twilight",
            "Sapphire",
            "Silhouette",
            "Mystic",
            "Dawn",
            "Lush",
            "Divine",
            "Bloom",
            "Celestial",
            "Enchanted",
            "Petal",
            "Moonlight",
            "Aurora",
            "Dusk",
            "Pearl",
            "Tranquility",
            "Blossom",
            "Dew",
            "Meadow",
            "Mirage",
            "Cascade",
            "Zen",
            "Solitude",
            "Breeze",
            "Mystical",
            "Harmony"
    };
}
